[package]
name = "mozilla-root-ca"
version = "2024.12.16"
authors = ["Delta4 <delta4chat@gmx.com>"]
edition = "2021"
description="Mozilla Root CA list from https://curl.se/ca/cacert.pem"
license="MPL-2.0"
repository="https://github.com/delta4chat/mozilla-root-ca"

[features]
default = []
pem = []
x509cert = ["dep:x509cert"]
x509-certificate = ["dep:x509-certificate"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
const-decoder2 = "0.5.1"
x509-certificate = { optional = true, version = "0.24.0" }
x509cert = { optional = true, version = "0.25.1" }

[dev-dependencies]
bytes = "1.9.0"

